-- Create Enum for billing
CREATE TYPE billing_cycle_type AS ENUM ('lifetime', 'monthly');

-- Create Ranks Table
CREATE TABLE ranks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price DECIMAL(10, 2) NOT NULL,
  billing_cycle billing_cycle_type NOT NULL DEFAULT 'monthly',
  color TEXT NOT NULL DEFAULT '#FED405',
  icon_name TEXT NOT NULL DEFAULT 'Shield',
  weight INTEGER NOT NULL DEFAULT 0,
  parent_rank_id BIGINT REFERENCES ranks(id) ON DELETE SET NULL,
  perks TEXT[] DEFAULT '{}',
  sale_price DECIMAL(10, 2),
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Enable RLS
ALTER TABLE ranks ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Enable read access for all users" ON ranks FOR SELECT USING (true);
CREATE POLICY "Enable all access for authenticated users" ON ranks FOR ALL USING (auth.role() = 'authenticated');
